version: '3.7'

services:
  # proxy:
  #   image: nginx:alpine
  #   container_name: proxy
  #   ports:
  #     - '80:80'
  #   volumes:
  #     - ./server/nginx.conf:/etc/nginx/nginx.conf
  #   restart: 'unless-stopped'
  #   networks:
  #     - backend
  postgres:
    image: postgres:14.4
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
    ports:
      - '5432:5432'
    networks:
      - backend
  server:
    build:
      context: ./server
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: password
      DB_DATABASE: dev
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - postgres
    depends_on:
      - postgres
  client:
    build:
      context: ./client
      target: development-build-stage
    container_name: client
    ports:
      - '3001:3001'
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      VITE_API_URL: http://localhost:3000
    networks:
      - backend
    depends_on:
      - server

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
  postgres-data:
    driver: local
